### ISSUE TITLE
Shame on you

### ISSUE THREAD

**Issue by ghost** [botika/tdwmstatus#1]
Shame on you !

Don't pretend to be author of all the used code, more than 90 percent of the code in here is copy and paste from my [dwm-bar.c](https://github.com/wifiextender/dotfiles/blob/master/archlinux-openbsd/home/frost/.config/dwm_scripts/dwm-bar.c) which I wrote back in februrary 2015 and several months later published the code in separate repository under the name [dwm-bar](https://github.com/wifiextender/pinky-bar/commits/master?page=4)

Here's a blog post that I wrote back in the day - https://wifiextender.github.io/#!post=openbox-to-dwm

and here is a picture with what the very first versions of my dwm-bar.c looked like ![](https://wifiextender.github.io/img/file/openbox-to-dwm/openbox-2-dwm.jpg)

Quoting just the header of "your program". 

``` cpp
/*
 * Compile with:
 * gcc -Wall -Wextra -O2 dwm-bar.c -o dwm-bar -lasound -lX11 
 *
 * author : Juan Aguilar Santillana
 * version : 2.74-1
 * date : 16/06/2015
 */
```

I did stumble upon such copy and paste snafus - https://github.com/search?l=C&q=status+bar&type=Repositories&utf8=%E2%9C%93,  but none of them was so dare to declare themselves as authors of the used code as the people at least provided a link from where the code was borrowed.

**Comment by botika** [comment]
Yeah right, you want your share of rights? do you not like it sticking? Please only real issues I have me excited for nothing.
